# This is a TOML document.

title = "go_cronjob Example"

[cronjob]
[cronjob.test_1]
name = "test_1"
cmd = "php test_1.php"
spec = "*/1 * * * *"

[cronjob.test_2]
name = "test_2"
cmd = "php test_2.php"
spec = "*/1 * * * *"
